AffiliateWP/AffiliateWP

templates/register.php
Fixes https://github.com/affiliatewp/AffiliateWP/issues/478
=> Make website URL & promotion method fields required for logged in users

includes/admin/referrals/new.php
https://github.com/affiliatewp/AffiliateWP/issues/525
=> change divs to p

includes/admin/tools/class-recount.php, includes/affiliate-functions.php, includes/class-db.php, includes/class-referrals-db.php, includes/class-tracking.php, includes/creative-functions.php, includes/integrations/class-base.php, includes/integrations/class-edd.php, includes/integrations/class-pmp.php, includes/referral-functions.php
Fixes: https://github.com/affiliatewp/AffiliateWP/issues/506
=> Add affwp_post_update() hook

includes/class-affiliates-db.php, includes/class-creatives-db.php, includes/class-referrals-db.php, includes/class-visits-db.php
=> Remove backticks from table definitions

includes/class-affiliates-db.php
=> fix for issue #534 - Sorting affiliates by name clears list

includes/admin/tools/tools.php, languages/affiliate-wp-en.po
‘Use this tool create’ -> ‘Use this tool to create’
=> Minor typo correction

includes/class-integrations.php, includes/integrations/class-sproutinvoices.php
=> Sprout Invoices Integration

includes/class-creatives.php
=> Fixes #550

includes/integrations/class-sproutinvoices.php
Addresses issues found with the PR from #575.
sigh...sorry about not testing this stuff out *fully* before sending you a PR earlier.
=> SI Integration Bug fixes

includes/admin/class-welcome.php
=> first pass at welcome screen

templates/register.php
=> remove required class

includes/emails/actions.php
=> Add $referral to the args array so it can be used in email filters

affiliate-wp.php, includes/install.php, uninstall.php
For sanity... while we still can.
=> Instantiate all objects on plugins_loaded

includes/affiliate-functions.php, includes/class-register.php
Replace affiliate_wp()->affiliates->add() with affwp_add_affiliate(). Fixes #679
=> Fix email not being sent to affiliate

includes/class-tracking.php
=> ignore $0.00 referrals in conversion script

includes/emails/actions.php
=> Add affwp_notify_on_new_referral filter

includes/admin/creatives/actions.php, includes/affiliate-functions.php, includes/class-shortcodes.php, includes/creative-functions.php
=> add support for query strings

assets/css/forms.css
=> Add default styling for pre and code tags

includes/affiliate-functions.php, includes/referral-functions.php
=> Add a  parameter to affwp_get_affiliate_rate() to resolve #685

includes/integrations/class-memberpress.php
=> Use transaction ID for one time payments in memberpress. #702

includes/admin/affiliates/affiliates.php
This would be very helpful for the plugin I'm developing.
=> Add filter to affiliates bulk actions.

templates/dashboard-tab-referrals.php
These actions will allow plugins to extend the table columns and add other functions above and below the table. 
I am developing a plugin to convert affiliate commissions to 'Woocommerce Points & Rewards' points. I would like to add front end user actions to the mix.
=> Add 4 actions to the referrals dashboard template

assets/css/forms.css
Fixes #734
Note, we'll need to minimise the CSS. Wonder if we should get some grunt action going?
=> add bottom margin

assets/css/forms.css
=> Add bottom margin to dashboard menu

assets/css/forms.css
=> Add default border

assets/css/forms.css
=> Add spacing and border

templates/dashboard-tab-creatives.php, templates/dashboard-tab-referrals.php, templates/dashboard-tab-visits.php
=> change div to p

includes/admin/class-upgrades.php, includes/integrations/class-gravityforms.php
This PR extends what was done in #700 for #609 in light of [this decision](https://github.com/affiliatewp/AffiliateWP/pull/790#issuecomment-123927628) made recently in #624.
I also went ahead and changed to using a `affwp_` prefix for the custom setting key rather than `gform_`. The latter makes it sound like it's a setting coming from Gravity Forms. I think it's more appropriate to use our prefix here. Let me know if you agree @pippinsplugins.
=> Issue/609 (revised)

includes/class-creatives.php, templates/creative.php
=> Add support for creative.php template file, #595

includes/class-integrations.php, includes/integrations/class-s2member.php
=> Add s2member integration. #112

includes/affiliate-functions.php
=> Support fragment identifier in affwp_get_affiliate_referral_url()

assets/css/admin.css
=> Fix table issues with long affiliate names

includes/admin/class-upgrades.php
=> Create 1.7.3 update routine, fix rate adjustment.

includes/integrations/class-gravityforms.php
=> Change input value to 1

includes/affiliate-functions.php
=> Fix affiliate status

includes/class-tracking.php
=> Check for affiliate

includes/admin/tools/tools.php
=> added the word "to"

includes/class-register.php, includes/class-tracking.php, includes/misc-functions.php
=> Fix issues with spaces in usernames

assets/css/forms.css
=> Add cursor: pointer;

includes/class-login.php
=> Allow login by username

includes/class-register.php
=> Disallow numeric user names

templates/login.php
=> Change login for field IDs to prevent conflict with registration form

includes/admin/affiliates/affiliates.php, includes/admin/creatives/creatives.php, includes/admin/referrals/referrals.php
=> Add nonce checks to bulk action

includes/admin/class-notices.php
=> Add dismissable notice if no integrations are enabled

includes/integrations/class-memberpress.php
=> Add support for MemberPress coupon tracking

includes/admin/settings/class-settings.php
=> Update settings to match WordPress form field standards

includes/integrations/class-pmp.php
=> Add coupon tracking to PMP

templates/dashboard-tab-stats.php
=> Change action hook name

includes/class-integrations.php
Changed from WP e-Commerce to WP eCommerce
=> Adjust WP e-Commerce name

includes/integrations/class-exchange.php
This is a fix for #898. Not 100% tested yet, though.
=> Fix for PayPal and Exchange

.travis.yml, package.json
=> Update our tests for Travis to consume

includes/integrations/class-gravityforms.php
=> Default to form title

includes/emails/actions.php
=> Rewrite conditional so email can send

affiliate-wp.php, includes/admin/settings/class-settings.php, includes/class-rewrites.php, includes/class-tracking.php, includes/install.php, includes/integrations/class-exchange.php, includes/integrations/class-woocommerce.php, includes/integrations/extras/class-exchange-feature.php
=> New Affiliate_WP_Rewrites class

includes/admin/class-notices.php
=> link to integrations tab

includes/admin/tools/export/class-export-affiliates.php, includes/admin/tools/export/class-export-referrals-payout.php, includes/admin/tools/export/class-export-referrals.php, includes/admin/tools/export/class-export.php, includes/admin/tools/export/export.php
=> Fix export phpdocs

includes/integrations/class-zippycourses.php
This Pull Request fixes https://github.com/affiliatewp/AffiliateWP/issues/958, which was being caused by Paypal's IPNs creating orders without the Affiliate Cookies present. This update stores the cookies on Zippy's "Transaction" posts, and allows for these to be retrieved/saved when creating the referral. This has been tested with both Paypal and Stripe to confirm both are working post-updates.
If there are any issues with formatting, or this doesn't work as expected on the user who reported the issue's site, let me know and I can modify as necessary.
=> Add affiliate information to Zippy Courses Paypal Transactions. Fixes #958 

includes/integrations/class-exchange.php
=> check for guest email address

includes/integrations/class-gravityforms.php
=> Fix referral descriptions

includes/integrations/class-zippycourses.php
=> calculate product referral rates

includes/integrations/class-rcp.php
=> Set rate to null if product rate is not set in RCP. #980

includes/admin/class-upgrades.php, includes/admin/settings/class-settings.php
=> Remove duplicate rejection email settings. #986

templates/dashboard-tab-referrals.php
=> Make table cell span 4 columns

includes/plugin-compatibility.php
=> Fix redirects

includes/class-shortcodes.php, includes/scripts.php
=> register forms.css early and enqueue when required

assets/css/admin.css
=> Add padding

.travis.yml
=> Add PHP 7 to Travis

includes/admin/ajax-actions.php
Use sql to search instead of grabbing (potentially) large number of users from db - fixes #1021
=> Improved user search

includes/class-referrals-db.php, includes/referral-functions.php
=> Don't allow empty referral status when updating referrals Issue/1042

includes/admin/referrals/referrals.php
=> add affwp_referral_affiliate_column filter

includes/class-shortcodes.php
=> Don't run affiliate area if in admin and NOT doing ajax. #867

includes/class-visits-db.php, includes/visit-functions.php, tests/test-visits.php
=> First pass at handling referral var removal in pretty permalinks

templates/dashboard-tab-urls.php
=> Decode affiliate URL so that emails are shown properly. #1054

includes/class-tracking.php
=> Don't allow cookie expiration to go past 2038. #812

includes/admin/affiliates/affiliates.php, includes/admin/referrals/referrals.php, includes/admin/visits/visits.php
=> Make affiliate and referral tables extensible - Issue/895

templates/creative.php
=> remove getimagesize()

includes/class-graph.php
=> Filter yesterday graph as intended

includes/integrations/class-woocommerce.php
=> Allow rejected referrals to be updated in WooCommerce. #1077

includes/scripts.php
=> correct shortcode conditional

includes/class-tracking.php
Would allow custom slugs: https://github.com/AffiliateWP/AffiliateWP/issues/455#issuecomment-103339221
=> Pass $login to affwp_tracking_get_affiliate_id

includes/admin/AFFWP_Plugin_Updater.php, includes/admin/class-notices.php, includes/admin/settings/class-settings.php
=> Prevent downed site from affecting customers - Issue/1086

includes/admin/settings/class-settings.php, includes/affiliate-functions.php
=> First pass at default referral URL

includes/plugin-compatibility.php
=> Prevents OptimizeMember redirect

includes/admin/creatives/edit.php, includes/admin/creatives/new.php
=> Add maxlength to creative text field

includes/admin/affiliates/affiliates.php
First pass, adding the username column
#959
=> Add username column to affiliates page

includes/plugin-compatibility.php
=> Block redirect

includes/class-register.php
=> Add affiliate while creating new user

templates/dashboard-tab-urls.php
=> Add new hook

.travis.yml
- Added WordPress 4.4 single and multisite builds
- Added WordPress 4.3 multisite build
=> Add PHP nightly and composer self-update to Travis

templates/dashboard.php
This is a followup to #1162 for #1097.
=> Fix an errant parenthesis in dashboard.php following – #1097

includes/plugin-compatibility.php
=> Added action to disable mandrill filter prior to sending emails

includes/class-referrals-db.php
=> Remove duplicative cache flush from the add() method in the referrals DB subclass

includes/affiliate-functions.php, includes/class-db.php
=> Fire a new action immediately before an affiliate record is updated

includes/admin/settings/class-settings.php, includes/misc-functions.php, tests/test-misc-functions.php
=> Keep a float afloat when formatting amounts with thousands separators

includes/admin/AFFWP_Plugin_Updater.php, includes/admin/add-ons.php, includes/admin/class-addon-updater.php, includes/admin/class-welcome.php, includes/admin/settings/class-settings.php, includes/class-affiliates-db.php, includes/class-campaigns-db.php, includes/class-creatives-db.php, includes/class-referrals-db.php, includes/class-visits-db.php, includes/install.php
=> issue/1178 – Replace magic numbers used for cache expiration with self-documenting constants

includes/class-affiliates-db.php, tests/affiliates/test-affiliate-db.php
Issue: #960 
Adds tests for searching based on individual fields and both.
=> issue/960 – Add support for searching affiliates by their username

includes/admin/class-notices.php
=> issue/1078 – Make license notices dismissable for 2 weeks at a time

includes/admin/tools/class-migrate-affiliates-pro.php
=> Set email, rate, and earnings to empty string if empty. #1036

includes/admin/overview/overview.php, includes/affiliate-functions.php, tests/affiliates/test-affiliate-functions.php
Make affiliate status string translatable, related test (fixes #997)
=> Make affiliate status string translatable, related test (fixes #997)

.travis.yml, includes/class-affiliates-db.php, includes/class-creatives-db.php, includes/class-referrals-db.php, includes/class-visits-db.php
=> Improve defaults logic in query building functions

.travis.yml, includes/class-db.php
=> Add missing DocBlocks to Affiliate_WP_DB

includes/integrations/class-rcp.php
=> issue/1116 – rewrite update_discount_affiliate()

includes/class-referrals-db.php
=> issue/1231 - wrap contexts properly

assets/js/tracking.js
=> Issue / 1002

.gitignore
Ignore composer lock file and vendor directory. Fixes #1333.
=> Ignore composer lock file and vendor directory. Fixes #1333.

includes/misc-functions.php
=> Add support for the Argentine peso

includes/admin/user-profile.php
=> Do not show affiliate registration options in user profile if current user cannot manage affiliates

includes/class-integrations.php, includes/integrations/class-lifterlms.php
Adds LifterLMS integration.
Base is master at 37c3fb63. Implements #1365.
=> Adds LifterLMS integration

includes/admin/settings/class-settings.php
=> issue/1387 - Rename "Notify Admins" admin option

includes/integrations/class-memberpress.php
=> issue/1375 – Mark confirmed subscriptions as completed referrals.

includes/admin/affiliates/new.php
=> issue/71 - Change 'screen' to 'form'

includes/integrations/class-woocommerce.php
=> issue/1427 - Add WooCommerce product settings to custom tab. #1427

languages/affiliate-wp-es_ES.po
The previous translations aren't suitable for Spanish users ;) 
Issue #1502
=> issue/1502 - Much better translation

includes/misc-functions.php
=> issue/1534 - Switch out the Iranian Toman for the Rial

includes/admin/tools/class-migrate-users.php, includes/admin/tools/class-migrate.php
... for easier debugging.
Resolves #1545
=> issue/1545 - Add basic logging/fix user migration beyond the first 100 users

includes/integrations/class-edd.php
=> Introduce option to disable referrals on license upgrades. #1308

includes/class-register.php, templates/register.php
=> issue/1008 - Unhide affiliate registration fields

.gitignore
- Addresses #1643
- Re-created with master as base.
=> Remove docs dir from ignore list

includes/admin/settings/class-settings.php
=> Ensure checkins only run once per week. #1648

includes/integrations/class-woocommerce.php
=> Remove $posted parameter to solve #1652

includes/admin/affiliates/screen-options.php, includes/admin/class-menu.php, includes/admin/creatives/screen-options.php, includes/admin/payouts/screen-options.php, includes/admin/referrals/screen-options.php, includes/admin/visits/screen-options.php, includes/misc-functions.php
=> Issue/1661 - Resolve screen option loading in non-English sites

includes/class-referrals-db.php, tests/referrals/test-referral-db.php
=> Add where statement for payout_id parameter in get_referrals(). #1651

tests/affiliates/test-affiliate-functions.php
=> Issue/1656 – Flat rate tests

includes/admin/tools/export/class-export-referrals-payout.php, includes/admin/tools/export/class-export.php
=> issue/1678 – Avoid recursion caused by a dynamic hook name conflict

includes/admin/affiliates/edit.php
=> issue/1382 – Output an affiliate\'s referral URL on Affiliate Edit.

includes/abstracts/class-affwp-list-table.php, includes/admin/affiliates/class-list-table.php
=> issue/1573 – Link the affiliate name to Edit Affiliate, swap 'Edit' row link for 'Edit User'

includes/integrations/class-edd.php, includes/integrations/class-exchange.php, includes/integrations/class-memberpress.php, includes/integrations/class-rcp.php, includes/integrations/class-woocommerce.php
=> Only look up affiliate ID if one was retrieved from coupon. #1689

templates/no-access.php
=> Add admin-only message to affiliate area - issue/1251

includes/admin/payouts/view.php
=> issue/1686 – Show the 'Actions' column when listing referrals in View Payout.

includes/admin/ajax-actions.php
=> Issue/1704 – Help affwp_search_users() be more scalable

includes/affiliate-functions.php
=> issue/1727 – Remove a redundant user_id check in affwp_add_affiliate()

includes/admin/affiliates/class-list-table.php
=> issue/1611 – Change 'Earnings' to 'Paid Earnings' in the affiliates list table

includes/admin/overview/metaboxes/class-metabox-overview-most-valuable.php, includes/admin/overview/metaboxes/class-metabox-overview-recent-referral-visits.php, includes/admin/overview/metaboxes/class-metabox-overview-recent-referrals.php, includes/admin/overview/metaboxes/class-metabox-overview-registrations.php, includes/admin/overview/metaboxes/class-metabox-overview-totals.php, includes/admin/overview/overview.php
=> issue/1694 – Explicitly instantiate Overview meta box classes in the loading order

assets/js/frontend.js
=> issue/1690 – Remove whitespace from campaign names on focusout

includes/REST/v1/class-affiliates-endpoints.php, includes/REST/v1/class-creatives-endpoints.php, includes/REST/v1/class-payouts-endpoints.php, includes/REST/v1/class-referrals-endpoints.php
=> Issue/1740 – Set reasonable default limits for core object REST endpoints

includes/affiliate-functions.php, includes/creative-functions.php, includes/payout-functions.php, includes/referral-functions.php, includes/visit-functions.php
=> issue/1750 – Pass the object types for all core object deletion wrapper functions.

includes/admin/settings/class-settings.php
=> issue/1759 – Avoid self-pinging affiliatewp.com.

templates/dashboard.php
=> Issue/1778 - Move hook before log out link

includes/admin/user-profile.php, includes/emails/actions.php
=> issue/1271 – Add user option to disable affiliate acceptance email on approval

includes/misc-functions.php
=> Issue/1791 - Add Kazakhstani Tenge

includes/class-graph.php
=> issue/1755 – Always attach the inline graph JS to the end of the jquery-flot script

includes/admin/add-ons.php, includes/admin/reports/class-reports-admin.php, includes/admin/settings/display-settings.php, includes/admin/tools/tools.php, includes/misc-functions.php
=> issue/1763 – Introduce affwp_navigation_tabs() to output nav tabs in various AffWP screens

includes/abstracts/class-affwp-reports-tab.php, includes/admin/reports/class-registrations-graph.php, includes/class-referrals-graph.php, includes/class-visits-graph.php
=> Issue/1775 – Reports performance improvements

includes/admin/class-notices.php, includes/admin/tools/class-migrate-affiliates-pro.php, includes/admin/tools/class-migrate-base.php, includes/admin/tools/class-migrate-users.php, includes/admin/tools/class-migrate-wp-affiliate.php, templates/dashboard.php
=> Issue/397 – Add migrated items counts to the admin notices displayed upon finishing

includes/admin/referrals/class-list-table.php
=> Issue/1810 – Restore the affwp_referral_action_links hook to the referrals list table

includes/admin/affiliates/edit.php
=> Issue/1851 - Make textarea field consistent

includes/admin/affiliates/view.php, includes/admin/tools/export/class-export-affiliates.php
=> Issue/1841 - Add conversion rate to affiliate reports

includes/REST/v1/class-affiliates-endpoints.php, includes/REST/v1/class-creatives-endpoints.php, includes/REST/v1/class-payouts-endpoints.php, includes/REST/v1/class-referrals-endpoints.php, includes/REST/v1/class-rest-controller.php, includes/REST/v1/class-visits-endpoints.php, includes/class-referrals-db.php
=> Issue/1825 – Schema support for core REST endpoints (WIP)

affiliate-wp.php, includes/admin/class-upgrades.php, includes/class-capabilities.php
Issue: #1830 
**New primitive caps:**
**New meta caps:**
=> Issue/1830 – Moar capabilities

includes/misc-functions.php
=> Issue/1518 - Add Pakistani PKR

includes/class-integrations.php, includes/integrations/class-pms.php
=> issue/1710 – Added Paid Member Subscriptions integration

assets/js/frontend.js
- Account for spaces in affiliate usernames in affiliate URLS
- Fixes #843
=> issues/843: Encode space characters in affiliate URL generator

includes/scripts.php, templates/dashboard-tab-visits.php
=> issue/1847 – Only enqueue dashicons on the front-end when needed.

includes/admin/class-notices.php
=> issue/1824 – Correctly reflect 1 affiliate was added when performed manually

includes/admin/tools/export/class-export-referrals.php
=> issue/1473 – Add slashing to each referral description on CSV export

assets/js/admin.js
=> Enforce mm/dd/yyyy format on date picker to solve #1845

includes/scripts.php, templates/register.php
=> issue/1854 – More selectively enqueue affwp-recaptcha to maintain compat with GF

includes/REST/v1/class-payouts-endpoints.php, includes/admin/class-menu.php, includes/admin/tools/import/import.php, includes/admin/tools/tools.php
Issue: #1830
Begins implementation of new primitive and meta capabilities introduced in #1831. This isn't intended to cover _everything_, mostly just the obvious ones that could be better targeted. We'll handle moving to the new meta capabilities in a separate PR.
=> issue/1830 – Implement new primitive and meta caps

includes/integrations/class-paypal.php
=> Add auto rejection for PayPal integration. #1629

includes/admin/creatives/class-list-table.php
=> Issue/1280 - Add image preview to main list table

includes/admin/affiliates/edit.php, includes/affiliate-functions.php
=> Issue/1837 - Allow affiliate status to be changed from edit screen

assets/css/forms.css
=> Issue/1538 - Remove label/input widths

templates/dashboard-tab-creatives.php, templates/dashboard-tab-graphs.php, templates/dashboard-tab-referrals.php, templates/dashboard-tab-settings.php, templates/dashboard-tab-stats.php, templates/dashboard-tab-urls.php
$affiliate_id instead of affwp_get_affiliate_id()
#1882
=> Issue/1882 - Remove extra calls

affiliate-wp.php, includes/admin/AFFWP_Plugin_Updater.php, includes/admin/settings/class-settings.php
=> Issue/1885 – Add setting to opt in to beta releases

includes/class-integrations.php, includes/integrations/class-give.php
=> Issue/1009 - Give integration WIP

includes/admin/affiliates/review.php, includes/admin/creatives/edit.php, includes/admin/creatives/new.php, includes/admin/overview/metaboxes/class-metabox-overview-totals.php, includes/admin/referrals/edit.php, includes/admin/settings/class-settings.php, includes/admin/tools/tools.php
=> Issue/1531 - Make admin copy consistent

includes/class-integrations.php, includes/integrations/class-wpforms.php
=> Issue/1380 - WPForms integration

templates/login.php, templates/register.php
=> Issue/1917 - Adjust copy on login and register templates

includes/admin/referrals/class-list-table.php
=> issue/1907 – Add an affiliate filter field to the Referrals list table.

includes/class-referrals-db.php
=> issue/1937 – Explicitly sanitize referral fields on update

assets/js/tracking.js, includes/class-tracking.php
=> Issue/1630 – JavaScript debug info API

includes/class-referrals-db.php
=> issue/1943 – affwp_increase_affiliate_unpaid_earnings() needs 2 args

includes/class-referrals-db.php, tests/referrals/test-referral-db.php
=> issue/1940 – Ensure count_by_status() can accept 'today'

assets/css/admin.css, assets/js/admin.js, includes/admin/class-upgrades.php
=> Issue/1707 – Tweak display of progress bar and success messages

assets/js/admin.js
=> issue/1952 – Only add postbox toggles for affwp admin pages.

includes/admin/overview/metaboxes/class-metabox-overview-most-valuable.php
=> issue/1976 – Add amount formatting to Most Valuable Affiliates table columns

tests/creatives/test-creative-db.php
=> issue/1983 – Add tests for creatives->count() and ->add().

assets/css/admin.css, includes/admin/tools/tools.php
=> issue/1953 – Add a download option for the debug log

includes/affiliate-functions.php
=> issue/1994 – Use affwp_format_rate(), adjust docs.

includes/admin/tools/tools.php
=> issue/1904 – Improve the debug log description.

includes/REST/class-rest-consumers-db.php, includes/admin/tools/system-info.php, includes/class-campaigns-db.php, tests/campaigns/test-campaign-db.php
=> Issue/2012 – Add object counts to system info log

includes/admin/tools/export/class-batch-generate-payouts.php
=> issue/1979 – Make the csv_cols() and get_data() methods in Generate_Payouts filterable

includes/admin/tools/system-info.php
=> issue/2011 – Add required registration fields to system log. Consolidate registration settings

includes/admin/AFFWP_Plugin_Updater.php
=> issue/1970 – Update AFFWP_Plugin_Updater to 1.6.10

includes/admin/affiliates/class-list-table.php
=> Issue/2016 - Add action hook to process_bulk_action()

includes/class-tracking.php
=> Issue/2026 - Use get_affiliate_id_from_login()

languages/affiliate-wp-es_ES.po
New and modified chains (upload the .mo file too)
=> es_ES .po file translation for v2.0.2

includes/class-tracking.php, tests/test-tracking.php
=> Issue/2035 – Refactor get_affiliate_id_from_login() with tests

includes/admin/AFFWP_Plugin_Updater.php
=> Update plugin updater class #2051 issue/2051

includes/affiliate-functions.php
=> Issue/2033 - Fix undefined index

assets/js/frontend.js
=> issue/1998 – Trim whitespace from the incoming URL in the URL generator.

includes/emails/functions.php, tests/emails/test-email-functions.php
=> issue/1912 – Change default empty rejection reason to empty string + tests

includes/referral-functions.php, tests/referrals/test-referral-functions.php
=> issue/1972 – Sanitize the rate amount before calculating the affiliate rate.

includes/admin/tools/system-info.php
=> issue/2064 – Add Credit Last Referrer setting to System Info log

assets/js/admin.js
=> issue/2067 – Ensure arr is defined in isArray.

includes/integrations/class-caldera-forms.php
=> Issue/2075 - Fix syntax error

includes/admin/class-notices.php
=> issue/2101 – Compare an actual version value in class-notices.php

affiliate-wp.php, includes/abstracts/class-affwp-registry.php, includes/admin/utilities/class-batch-process-registry.php, tests/test-registry.php
=> issue/2104 – Abstract out the Registry class for reuse elsewhere in core

includes/integrations/class-woocommerce.php
=> issue/2108 – Add Affiliate Area to the WC My Account menu

includes/REST/class-rest-consumers-db.php, includes/class-affiliates-db.php, includes/class-campaigns-db.php, includes/class-creatives-db.php, includes/class-payouts-db.php, includes/class-referrals-db.php, includes/class-visits-db.php
=> issue/2111 – Ensure $last_changed gets reinitialized

.gitattributes, .github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
=> issue/2113 – Add CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md files

includes/admin/class-upgrades.php, includes/admin/utilities/class-upgrade-registry.php, includes/class-utilities.php, includes/misc-functions.php
=> issue/2105 – Introduce a registry for upgrade routines

includes/admin/tools/export/class-batch-export.php, includes/admin/tools/export/class-export-settings.php, includes/admin/tools/export/class-export.php, includes/admin/tools/system-info.php
=> Issue/2040 – Remove safe_mode checks from core. 

includes/admin/tools/system-info.php
=> issue/2121 – Add the Affiliate Area Forms setting to the System Info log

assets/css/admin.css
=> Issue/2081 - Improve creative admin CSS

includes/scripts.php, tests/test-scripts.php
=> issue/2096 – includes/scripts.php test coverage

includes/admin/referrals/edit.php, includes/admin/referrals/new.php, includes/class-referrals-db.php, includes/referral-functions.php, tests/referrals/test-referral-functions.php
=> Issue/2132 – Add 'custom' support affwp_add_referral()

includes/admin/affiliates/class-list-table.php
=> issue/2152 – Handle deleting affiliates as a bulk action.

assets/css/forms.css
=> Issue/2143 - Remove background on code blocks inside creatives

includes/admin/tools/class-rest-consumers-table.php, includes/admin/tools/tools.php, includes/admin/visits/visits.php
=> Ensure affiliate autocomplete only finds non-affiliates in very specific contexts

templates/emails/header-default.php
=> Issue/2168 - Only show markup if heading is set

includes/integrations/class-base.php, includes/integrations/class-caldera-forms.php, includes/integrations/class-contactform7.php, includes/integrations/class-edd.php, includes/integrations/class-exchange.php, includes/integrations/class-give.php, includes/integrations/class-gravityforms.php, includes/integrations/class-lifterlms.php, includes/integrations/class-marketpress.php, includes/integrations/class-membermouse.php, includes/integrations/class-memberpress.php, includes/integrations/class-ninja-forms.php, includes/integrations/class-optimizemember.php, includes/integrations/class-paypal.php, includes/integrations/class-pmp.php, includes/integrations/class-pms.php, includes/integrations/class-rcp.php, includes/integrations/class-s2member.php, includes/integrations/class-shopp.php, includes/integrations/class-stripe.php, includes/integrations/class-woocommerce.php, includes/integrations/class-wpeasycart.php, includes/integrations/class-wpec.php, includes/integrations/class-wpforms.php, includes/integrations/class-zippycourses.php
=> Issue/2165 – Remove now-moot $this->debug checks in integrations

includes/abstracts/class-affwp-list-table.php, includes/admin/affiliates/class-list-table.php, includes/admin/creatives/class-list-table.php, includes/admin/payouts/class-list-table.php, includes/admin/referrals/class-list-table.php, includes/admin/visits/class-list-table.php
=> issue/2149 – Use the current item query to determine the total number of items for pagination

.travis.yml, includes/admin/tools/tools.php
=> issue/2128 – Bump WP minimum to 4.5

templates/dashboard-tab-visits.php
=> Always enqueue dashicons on the visits tab w/ affwp_enqueue_style()

includes/integrations/class-woocommerce.php
=> issue/2182 – WooCommerce 3.0 compat

affiliate-wp.php, includes/integrations/class-woocommerce.php, package.json, templates/register.php
=> Issue/2190 - Add double quotation marks

uninstall.php
=> issue/2159 – Loop through all sites to delete database tables on uninstall

includes/class-graph.php, tests/test-graph.php
=> Issue/1773 – Ensure the correct month start is used to calculate end of month for report dates

includes/class-register.php
=> Issue/2196 - Remove extra status

includes/class-referrals-db.php, tests/referrals/test-referral-db.php
=> Issue/2202 – Refine paid_earnings() query

includes/integrations/class-base.php
=> Use empty instead of isset since isset is truthful on 0 values. #2206

includes/admin/tools/export/class-batch-export-affiliates.php, includes/admin/tools/export/class-batch-export-payouts.php, includes/admin/tools/export/class-batch-export-referrals.php
=> issue/2211 – Pass returns from get_data() through prepare_data() filters

includes/affiliate-functions.php, includes/class-affiliates-db.php, tests/affiliates/test-affiliate-db.php, tests/affiliates/test-affiliate-functions.php
=> issue/2218 – Actually add support for setting date_registered when adding affiliates

includes/integrations/class-woocommerce.php
=> issue/955 – Register a verbose rewrite rule to handle the shop as product base

includes/class-affiliates-db.php, tests/affiliates/test-affiliate-db.php, tests/affiliates/test-affiliate-functions.php, tests/phpunit/affwp-testcase.php
=> Issue/2225 – gmt_offset should not be used when adding affiliates with a given date_registered

includes/admin/affiliates/actions.php, includes/affiliate-functions.php, includes/class-affiliates-db.php, includes/class-register.php, tests/admin/test-actions.php, tests/affiliates/test-affiliate-db.php, tests/affiliates/test-affiliate-functions.php
=> Issue/2227 – Set user website URL while adding an affiliate

includes/class-tracking.php
=> Issue/2031 – Fall back to printing tracking header scripts on wp_footer

includes/admin/class-upgrades.php, includes/class-rewrites.php, includes/integrations/class-wpec.php
=> Issue/2077 – Add a rewrite rule for the products page + referral var

includes/class-tracking.php
=> Support Credit Last Referrer setting when fallback tracking is enabled - issue/2038

includes/install.php, uninstall.php
=> issue/2101 – Simply mark past upgrade routines complete for all sites on AffWP install

includes/admin/settings/class-settings.php
=> issue/2028 – Add an AffWP + WooCommerce + Polylang note to the 'referral_pretty_urls' setting

includes/misc-functions.php, tests/misc/test-misc-functions.php, tests/referrals/test-referral-functions.php
=> issue/1972 – Redo tests for calculating referral amounts with comma decimal separators

includes/misc-functions.php, templates/register.php, tests/misc/test-misc-functions.php
=> Issue/1919 – Use HTML5 validation on the registration form

includes/abstracts/class-affwp-reports-tab.php, includes/admin/reports/class-reports-admin.php, includes/admin/reports/class-reports-tab-registry.php
=> Issue/2248 – Reports tab registry

includes/REST/class-rest-consumers-db.php, includes/abstracts/class-db.php, includes/class-affiliates-db.php, includes/class-campaigns-db.php, includes/class-creatives-db.php, includes/class-payouts-db.php, includes/class-referrals-db.php, includes/class-visits-db.php, tests/test-db.php
=> Issue/2254 – Query for multiple fields

includes/REST/class-rest-consumers-db.php, includes/class-affiliates-db.php, includes/class-creatives-db.php, includes/class-payouts-db.php, includes/class-referrals-db.php, includes/class-visits-db.php, tests/affiliates/test-affiliate-db.php
=> Issue/2254 – Multi-field tests for object queries (WIP)

includes/REST/class-rest-consumers-db.php, includes/abstracts/class-db.php, includes/class-affiliates-db.php, includes/class-campaigns-db.php, includes/class-creatives-db.php, includes/class-payouts-db.php, includes/class-referrals-db.php, includes/class-visits-db.php, tests/affiliates/test-affiliate-db.php, tests/creatives/test-creative-db.php, tests/payouts/test-payouts-db.php, tests/phpunit/affwp-testcase.php, tests/referrals/test-referral-db.php, tests/test-db.php, tests/visits/test-visit-db.php
=> Issue/2263 – Consistent handling of empty values in the db layer

includes/admin/reports/tabs/class-payouts-reports-tab.php
=> issue/1997 – Affiliate-specific versions of all tiles in Reports > Payouts

includes/class-referrals-db.php, tests/referrals/test-referral-db.php, tests/referrals/test-referral-functions.php
=> Issue/2257 – Adjust earnings with status changes in update_referral() method

includes/integrations/class-paypal.php
=> issue/2245 – AFFILIATEWP_PAYPAL_IPN

includes/admin/referrals/class-list-table.php, includes/admin/referrals/contextual-help.php, includes/class-referrals-db.php, tests/referrals/test-referral-db.php
=> issue/2265 – Referral amount and description search

includes/admin/overview/metaboxes/class-metabox-overview-recent-referrals.php
=> issue/2247 – Format even empty amounts in Recent Referrals meta box

includes/admin/creatives/new.php
=> Issue/2249 – Skip image text for add creative

includes/class-payouts-db.php, tests/payouts/test-payouts-db.php
=> Issue/2230 – payout_id should not have a default value in payouts db

includes/integrations/class-woocommerce.php
=> issue/2289 – Only instantiate the WooCommerce integration class if WC is active

includes/integrations/class-caldera-forms.php, includes/integrations/class-contactform7.php, includes/integrations/class-edd.php, includes/integrations/class-exchange.php, includes/integrations/class-formidablepro.php, includes/integrations/class-give.php, includes/integrations/class-gravityforms.php, includes/integrations/class-jigoshop.php, includes/integrations/class-lifterlms.php, includes/integrations/class-marketpress.php, includes/integrations/class-membermouse.php, includes/integrations/class-memberpress.php, includes/integrations/class-ninja-forms.php, includes/integrations/class-optimizemember.php, includes/integrations/class-pmp.php, includes/integrations/class-pms.php, includes/integrations/class-rcp.php, includes/integrations/class-s2member.php, includes/integrations/class-shopp.php, includes/integrations/class-sproutinvoices.php, includes/integrations/class-stripe.php, includes/integrations/class-wp-invoice.php, includes/integrations/class-wpeasycart.php, includes/integrations/class-wpec.php, includes/integrations/class-wpforms.php, includes/integrations/class-zippycourses.php
=> Issue/2291 – Check if integration plugins are active before instantiating integration logic

includes/admin/ajax-actions.php, includes/admin/tools/tools.php
=> Issue/2299 – Only autocomplete affiliates

includes/install.php, uninstall.php
=> Issue/2305 – Don't deliberately load ms-bootstrap for non-ms

includes/admin/reports/tabs/class-payouts-reports-tab.php
=> issue/2307 – Ensure payout tiles are always supplied numbers they can use

includes/admin/visits/class-list-table.php
=> Do not overwrite number parameter for main visits list table query. issue/2313

includes/integrations/class-woocommerce.php
=> issue/2317 – Better My Account link logic for WooCommerce

includes/actions.php, includes/admin/affiliates/actions.php
=> Load affwp_process_add_affiliate_website() on front-end

includes/admin/class-upgrades.php
=> issue/2319 – Add an upgrade routine for 2.1.3.1 to refresh admin caps.

includes/misc-functions.php, tests/misc/test-misc-functions.php
=> issue/2321 – Only determine the thousands separator for thousands

includes/admin/ajax-actions.php
=> issue/2334 – Autocomplete users even if status=none

includes/admin/visits/class-list-table.php
=> Reorder visits table columns and add visit_id column. #1908

includes/admin/tools/class-rest-consumers-table.php
=> issue/2335 – Autocomplete affiliates of any status for API keys

languages/affiliate-wp-es_ES.po
New and fuzzy chains fully translated to es_ES
=> AffiliateWP v 2.1 Spanish (Spain)

includes/admin/settings/class-settings.php, includes/admin/settings/display-settings.php
=> recheck license key status on page load of general settings tab. #2342

includes/admin/tools/class-batch-recount-affiliate-stats.php, includes/admin/tools/export/class-batch-export-affiliates.php, includes/admin/tools/export/class-batch-export-payouts.php, includes/admin/tools/export/class-batch-export-referrals.php, includes/admin/tools/export/class-batch-export-visits.php, includes/admin/tools/export/class-batch-export.php, includes/admin/tools/export/class-batch-generate-payouts.php, includes/admin/tools/import/class-batch-import-affiliates.php, includes/admin/tools/import/class-batch-import-csv.php, includes/admin/tools/import/class-batch-import-referrals.php, includes/admin/tools/import/class-batch-import.php, includes/admin/tools/upgrades/class-batch-upgrade-recount-affiliate-stats.php, includes/admin/utilities/class-batch-migrate-users.php, includes/admin/utilities/class-batch-migrate-wp-affiliate.php, includes/admin/utilities/class-batch-process.php, includes/admin/utilities/class-data-storage.php
=> Issue/2358 – Batch process garbage collection

includes/misc-functions.php
=> issue/2331 – Add Kenyan Shilling 

includes/admin/settings/class-settings.php
Issue: #2365 
@michaelbeil Here you are
=> Remove bad \r

includes/integrations/class-rcp.php
=> issue/2389 - Use pending subscription name when adding pending referral. #2389

includes/integrations/class-give.php
- Updates Give integration to use new API
- #2393 - Pending addition of custom rate calculation (in progress)
=> issue/2393 - Update Give integration to use new API

includes/admin/reports/tabs/class-referrals-reports-tab.php
- Shows correct amount for provided date range in unpaid referrals, in the reports tab tile.
- #2355
=> Issue/2355 - Show correct totals for unpaid earnings in referral reports

includes/admin/AFFWP_Plugin_Updater.php
=> issue/2412 – Update AffWP_Plugin_Updater class to v1.6.15.

includes/integrations/class-woocommerce.php
=> Issue 2414 - Remove priority on woocommerce_product_data_panels hook

includes/admin/tools/import/class-batch-import-affiliates.php, includes/admin/tools/import/class-batch-import-referrals.php, tests/utilities/test-batch.php
=> Issue/2420 – Define batch import batch IDs

assets/css/forms.css
=> Issue 2434 - Simplify last chid ruleset

includes/admin/tools/export/class-batch-export-affiliates.php, includes/affiliate-functions.php, tests/affiliates/test-affiliate-functions.php
=> Introduce affwp_get_affiliate_last_name() and affwp_get_affiliate_first_name() - issue/2341

templates/dashboard-tab-referrals.php
=> Add reference column to affiliate area. #2340

includes/admin/settings/class-settings.php, includes/emails/actions.php
=> Add options to send site admin an email when new referrals are earned - issue/1839

languages/affiliate-wp-nl_NL.po
=> Wachwoord > Wachtwoord

includes/class-login.php, includes/class-register.php
=> Default to affiliate area page URL if no redirect is provided issue/2410

assets/css/admin.css, includes/admin/creatives/class-list-table.php
=> Issue/983 - Add bulk actions menu to Creatives

languages/affiliate-wp-es_ES.po
=> Solve fuzzy chains

templates/dashboard-tab-referrals.php
=> Issue/2452 - Update colspan

includes/integrations/class-base.php
=> issue/2200 - Only log a referral retrieval error when it's reasonable to assume an invalid referral is in play

includes/visit-functions.php, tests/visits/test-visit-functions.php
=> Issue/2419 – Allow usernames with dashes to be stripped from the visit URL on sanitization

includes/admin/tools/class-batch-recount-affiliate-stats.php, includes/admin/tools/tools.php
=> issue/2458 – Recount tool issues

includes/integrations/class-rcp.php
=> issue/2467 - Set $0 referral for RCP free trials

includes/emails/class-affwp-emails.php
=> Update description of {name} tag. #2443

includes/abstracts/class-db.php, tests/test-db.php
Issue: #2474
Previous discussion: #2475
=> issue/2474 – Introduce dynamic short-circuit filter into db->insert() for all objects.

includes/REST/v1/class-affiliates-endpoints.php, includes/REST/v1/class-rest-controller.php
=> Issue/2480 – Convert REST string params to objects where defined as such in the schema

includes/integrations/class-ninja-forms.php
=> Create referrals with the proper amount based on rate settings in Ninja Forms

includes/integrations/extras/class-ninja-forms-action-add-referral.php
Updated logic to prevent a second submission from taking place when submission ID is already set.
=> Update to resolve secondary submission on Ninja Forms Integrations

includes/integrations/class-woocommerce.php
=> Add Affiliate Referral column to orders table. #2288

includes/actions.php, includes/misc-functions.php, tests/misc/test-misc-functions.php
=> issue/2382 - Add Bitcoin currency

includes/misc-functions.php
=> issue/2382 – Add Bitcoin currency - #2382

includes/integrations/class-woocommerce.php
=> Prevent fatal error when order has been deleted in WooCommerce. #2505

includes/integrations/class-edd.php
=> Add price name to referral description for EDD integration. #2380

includes/integrations/class-woocommerce.php
=> issue/2411 - WooCommerce: Add link in order note to go directly to referral edit screen

includes/integrations/class-exchange.php
=> Issue/2514 - Referrals not created if non affiliate coupon is used in ExchangeWP. Fixes #2514

includes/admin/class-notices.php, includes/admin/payouts/class-list-table.php, includes/admin/referrals/actions.php
=> Issue/2362 - Add an option to delete payout(s) from the Payouts screen

includes/integrations/class-contactform7.php
=> Issue/2496 - Introduce a affwp_cf7_referral_description filter.

includes/admin/settings/class-settings.php, includes/emails/actions.php
=> Issue/2405 - Improve UI for disabling specific email notifications

includes/class-shortcodes.php
=> Issue/2534 - Add is_admin() conditional check

includes/class-integrations.php, includes/integrations/class-exchange.php
=>  Update iThemes Exchange to ExchangeWP #2504

assets/css/forms.css
#2508
Note: minified CSS file will need to be generated before release.
=> Issue/2508 - Make fields 100% width

includes/actions.php
=> Issue/2543 - Add register_affiliate to $query_args

includes/emails/actions.php
=> Issue/2516 - Add link to set password

assets/css/admin.css, includes/integrations/class-woocommerce.php
=> Issue/2531 - Adjust CSS on the affiliate column on the WC orders page

includes/admin/overview/metaboxes/class-metabox-overview-highest-converting-urls.php, includes/admin/overview/overview.php
=> Issue/63 - Add a highest converting urls metabox to the overview page. #63

includes/misc-functions.php
=> Force affwp_get_current_page_number() to return a min of 1. #2563

includes/integrations/class-edd.php
=> Issue/2560 - Add referral link to referral payment note in EDD integration. #2560

includes/integrations/class-edd.php
=> Issue/2559 - Fix wrong referral amount in EDD integration if cart is modified after pending referral has been created

includes/integrations/class-edd.php
=> Issue/2572 - Use ! empty()

includes/admin/class-notices.php, includes/admin/referrals/actions.php, tests/admin/test-notices.php
=> Issue/2570 - Display an error if the affiliate account is not valid when adding a new referral in the admin

assets/css/forms.css
=> Issue/2575 - Change selector used for creatives

includes/class-tracking.php
=> Issue/2578 - Fix affwp_campaign cookie not generated if fallback tracking is enabled

includes/integrations/class-woocommerce.php
=> Issue/2556 - Fix WooCommerce integration updating referral right after creating it

assets/css/admin.css, includes/integrations/class-woocommerce.php
=> Issue/2547 - Add affiliate referral to WooCommerce 3.3 preview order modal window

includes/integrations/class-ninja-forms.php, includes/integrations/extras/class-ninja-forms-action-add-referral.php
=> Issue/2594 - Wrong referral amount in the Ninja Forms integration.

includes/integrations/extras/class-ninja-forms-action-add-referral.php
=> Issue/2589 - Fix blank referral description in the Ninja Forms integration

includes/integrations/class-rcp.php
=> issue/2602 - RCP: Revoke referrals on refunded and abandoned payments. #2602

includes/integrations/class-rcp.php
=> Issue/2491 - Fix fatal error. #2491

includes/integrations/class-formidablepro.php
=> Issue/2598 - Fix fatal error(s)

includes/admin/tools/upgrades/class-batch-upgrade-create-customers.php, includes/class-affwp-customer.php, includes/integrations/class-caldera-forms.php, includes/integrations/class-edd.php, includes/integrations/class-give.php, includes/integrations/class-gravityforms.php, includes/integrations/class-ninja-forms.php, includes/integrations/class-woocommerce.php
=> Issue/2491 - Fix fatal error during upgrade routine & querying customer ids in the customermeta table

includes/admin/payouts/screen-options.php, includes/admin/payouts/view.php, includes/admin/referrals/class-list-table.php
=> Issue/2441 - Enable pagination from the payout screen

includes/class-tracking.php, includes/integrations/class-optimizemember.php, includes/integrations/class-s2member.php
=> Issue/2374 - Fix referral not always created in OptimizeMember integration

includes/admin/tools/export/class-batch-export-affiliates.php, includes/admin/tools/export/class-export-affiliates.php, includes/admin/tools/export/class-export.php, includes/admin/tools/export/export.php
=> Issue/1771 - Converts the character encoding when exporting data

affiliate-wp.php
Added `GitHub plugin URI` for more integration and information abilities.
=> Added GitHub plugin URI

includes/class-rewrites.php
=> Issue/2302 - Fix referral cookie creation for some custom permalink structure.

includes/integrations/class-jigoshop.php
=> Issue/2525 - Add support for Jigoshop eCommerce

includes/integrations/class-give.php
=> Issue/2662 - Fix incorrect referral amount in Give integration

includes/integrations/class-zippycourses.php
=> In ZippyCourses bail if order or customer is not retrieved. #2664

includes/admin/settings/class-settings.php, includes/class-register.php, includes/emails/actions.php, templates/register.php
=> Issue/2541 - Make affiliate registration password fields optional

includes/class-referrals-db.php, includes/integrations/class-base.php
=> Force empty description values to empty string. #2672

includes/admin/settings/class-settings.php
=> Include mention of multisite in shared cookie settingns. #2590

includes/admin/settings/class-settings.php, templates/register.php
=> Add label settings for terms of use checkbox. #2637

includes/admin/tools/export/class-batch-export-csv.php, includes/admin/tools/export/class-batch-generate-payouts.php
These changes allow payout generation even in the case of not having some referrals with affiliate_id=0 and/or losing the current_count option in the middle of the process.
Issue: #2369
=> issue/2369 - Changes to strengthen payout generation

includes/abstracts/class-db.php, includes/class-customers-db.php
=> Issue/2688 -  Fix PHP Notice and don't carry out update() operation if data to be updated is empty

includes/admin/settings/class-settings.php, includes/class-customers-db.php, includes/class-tracking.php, includes/class-visits-db.php, includes/integrations/class-base.php
=> Issue/2684 - Disable IP address logging

includes/integrations/class-optimizemember.php
=> Exit after payment notification is completed - issue/2699

includes/admin/affiliates/class-list-table.php, includes/admin/creatives/class-list-table.php, includes/admin/payouts/class-list-table.php, includes/admin/referrals/class-list-table.php, includes/admin/visits/class-list-table.php
=> Issue/2583 - Add filters to get_sortable_columns() methods

includes/emails/class-affwp-emails.php
=> Issue/2592 - Add make_clickable and fix broken links

includes/admin/affiliates/review.php
=> Issue/2568 - Add PayPal email to affiliate review page

includes/admin/creatives/edit.php, includes/admin/creatives/new.php, includes/creative-functions.php, templates/dashboard-tab-creatives.php
=> Issue/2173 – Creative description WYSIWYG

includes/integrations/class-base.php
=> Add debug log entry when referral not found by reference. #2701

includes/class-referrals-db.php
=> Issue/2709 - Fix invalid sql query in Affiliate_WP_Referrals_DB::get_referrals()

includes/integrations/class-woocommerce.php
=> Issue/2705 -Don't create referral when single product with referral disabled is purchased in WooCommerce

includes/integrations/class-woocommerce.php
=> Issue/2715 - Fix fatal error on WooCommerce checkout page if WooCommerce 2.X is installed

includes/admin/referrals/class-list-table.php
=> Issue/2718 - Fix issue with marking referrals as paid on the referrals page.

includes/emails/actions.php
=> Issue/2695 - Fix password reset link being added to email wrongly

includes/admin/referrals/class-list-table.php
=> Issue/2650 - Stay on current referrals page when accepting, rejecting, marking as paid or unpaid a referral

includes/integrations/class-formidablepro.php
=> Issue/2655 - Fix issue with completing and revoking referrals in Formidable Pro integration

includes/admin/visits/class-list-table.php, includes/class-visits-db.php
=> Issue/2210 - Search for exact urls on the Visits page using a url keyword prefix in the search box

languages/affiliate-wp-es_ES.po
=> 2.2.1 Spanish (Spain) Translation Update

includes/class-tracking.php
=> Issue/2722 - Add affwp_before_track_conversion action hook

includes/admin/affiliates/actions.php, includes/admin/affiliates/new.php, includes/admin/user-profile.php
=> Issue/2093 - Admin shortcut to add an existing user as a new affiliate

includes/class-customers-db.php
=> Issue/2711 - Updating a customer record should only add a new affiliate_id customer meta if it doesn't exist

includes/admin/referrals/class-list-table.php, includes/class-referrals-db.php
=> Issue/2729 - Fix fatal error when get_referrals() method returns invalid referrals in AffWP_Referrals_Table class

includes/integrations/class-paypal.php
=> Issue/2721 - Create customer when processing IPN in PayPal integration

includes/admin/referrals/class-list-table.php
=> Issue/2738 - Show referral ID column on referrals admin screen

includes/class-affiliates-db.php, includes/class-creatives-db.php, includes/class-payouts-db.php, includes/class-visits-db.php
=> Issue/2743 - Only select valid results when getting data 

includes/integrations/class-opt-in.php
=> Issue/2754 - Create customer record when creating a new referral via the Opt-In Form.

includes/class-referrals-db.php
=> Issue/2765 - Link guest customer to user profile if it exist when inserting a referral

includes/admin/referrals/edit.php
=> Issue/2761 - Fix referral edit screen does not display arrays / objects in the custom field.

includes/integrations/class-pms.php
=> Issue/2770 - Fix customer record not created in PMS integration for customers that are not logged in

includes/integrations/class-rcp.php
=> Issue/2772 - Fix customer record not created in RCP integration for customers that are not logged in
