AffiliateWP/AffiliateWP

- includes/integrations/class-woocommerce.php
In e8c76ade0913ed8fa80775ac3c5fba546d468b95 a closing bracket was lost on the new span. This fixes the currently broken markup.
> Fix missing closing bracket in integrations/class-woocommerce.php

- includes/integrations/class-woocommerce.php
After 384353a0c786ac7b1f3d7121155e92ece5e41f5b the `$cart_discount` variable is no longer used anywhere in the function.
> Remove a variable that's no longer used

- includes/class-integrations.php
actions aren't technically necessary but when I worked on my integration I was looking for an easy way to load up the Affiliate_WP_Base subclass at the ideal time, which I could not find. This is different than filtering the integrations via affwp_enabled_integrations becuase there's no way to have the loop load up the subclass since the file path is a constant (and defined).
> Integration hooks

- includes/integrations/class-woocommerce.php
A slightly saner way to get the order id in this case. Originally from #461
> If order_id is a post object, grab the id directly

- templates/dashboard-tab-creatives.php
Allow to add custom creatives, before or after the list
For example:
// add video embed code to affiliatewp creatives
function add_video_to_creatives() {
?>
<div class="affwp-creative">
<p>
</p>
<p>Copy and paste the following:</p>
<p>
</p>
</div>
<?php
}
add_action( 'affwp-before-first-creative', 'add_video_to_creatives' );
Already using it in my website and it's working great.
> Add hooks to creatives

- includes/class-register.php
Fixes #686 
@pippinsplugins look ok to you? Looks like it was using the function name, rather than the action hook name. Tested and both types of registration seem to work fine.
> change did_action()

- includes/class-affiliate-meta-db.php
Seems `init` is a bit late to register the affiliatemeta table with $wpdb, moving to `plugins_loaded` hook so that it's properly registered for (hopefully) all use cases. 
Had a function hooked into `affwp_post_update_affiliate` and when calling `affwp_update_affiliate_meta()` it was returning false because the table hadn't been registered for use.
> register affiliatemeta table as early as possible

- assets/css/forms.css
Fixes #669 
To try and simulate the issue on themes that don't have suitable styling I first removed 2015's default CSS for word-wrap which resulted in this:
Then I added the new `word-wrap` CSS rule to our tables which gives us:
It would be better if themes had this CSS rule on `.entry-content`, ie the wrapping content div but because themes can easily change this class it would be better if we applied it specifically to our tables.
> Add word-wrap CSS rule to tables

- includes/admin/settings/class-settings.php
Fixes `'affwp_settings_sanitize_' . $type` filter overridden by `'affwp_settings_sanitize'`
Related to https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2662
> Fixes $type filter overridden by general filter

- includes/integrations/class-pmp.php
This swaps the PMP Order Code with the Order ID, effectively linking the PMP Order to the Referral.
> Fix PMP Order ID & Reference Link

- includes/class-integrations.php
- includes/integrations/class-zippycourses.php
I spoke with @pippinsplugins 2 days ago about including ZippyCourses support in the next release of AWP (he mentioned at the end of this month).  Here is a PR with a jump start on the integration (it's working on our test servers with our various gateways).
Created and tested AWP + ZippyCourses integration.  Please contact support@zippycourses.com if you need a copy of Zippy Courses to test with, or if we can do anything else to expedite the inclusion of Zippy Courses as an integration with AWP.
> Added Zippy Courses integration for AffiliateWP

- includes/integrations/class-pmp.php
In some instances this will try and check for a coupon code when there is no code set which ends up causing PMPro to throw errors at checkout.
> making sure we have a code before we check it

- README.md
After changing the team name from to affiliatewp to AffiliateWP, we destroyed our precious badge. But, now we have a fancy badge once again.
> Restore Travis Build Status badge

- includes/referral-functions.php
affwp_add_referral() becomes a bit more helpful as a wrapper function for `affiliate_wp()->referrals->add( $args )` if it matches the return value.
Now, we can use the returned value of the referral to actually do something with the referral that was just added.  Woot!
All the falsey/truthy checks in core (maybe 1?) will still work fine, as 0 evaluates to false, and any other positive integer evaluates to true.
> Modify return type of affwp_add_referral()

- includes/admin/settings/class-settings.php
- includes/affiliate-functions.php
- includes/misc-functions.php
New `affwp_settings_referral_format` filter that we'll need for custom affiliate slugs.
> Allow referral format to be filtered

- includes/integrations/class-woocommerce.php
Fixes #1092
Prevents skipping over calculating the commission if the product is zero priced, but the affiliate has a flat rate referral type. 
A flat rate set for an affiliate should generate a flat rate referral, regardless if the product was priced at $0.00.
> Don't skip over calculating commission

- includes/class-register.php
- includes/emails/actions.php
#1144
Also adds 3 new email filters and prevents any of this from showing when the "Auto Register New Users" option is enabled in the affiliate settings, since this will create a new affiliate when the user is added anyway. This issue is only useful for those who have that setting off and want fine-tuned control over who gets added as an affiliate.
> Add option to disable affiliate accepted email

- includes/affiliate-functions.php
- templates/dashboard.php
- tests/test-affiliates.php
Significantly DRYs up templates/dashboard.php (yay!) in the process of allowing access to the page ID and URL.
Also adds some tests.
Issue: #1097
> Add filterable helpers for retrieving the Affiliates Area page ID and URL – #1097

- includes/admin/class-upgrades.php
- includes/admin/settings/class-settings.php
- includes/admin/tools/import/import.php
- includes/install.php
- tests/admin/test-settings.php
- tests/test-misc-functions.php
Issue: #1171
Related discussion: #999 
The new `Affiliate_WP_Settings::set()` method accepts an array of setting `key => value` pairs and an optional `save()` trigger.
I've implemented the `save()` method as protected, currently only to be called via the optional third parameter in `set()`. We can always switch this to public later if the need arises.
**Basic single setting usage:**
```php
$affiliate_area = wp_insert_post(
array(
'post_title'     => __( 'Affiliate Area', 'affiliate-wp' ),
'post_content'   => '[affiliate_area]',
'post_status'    => 'publish',
'post_author'    => 1,
'post_type'      => 'page',
'comment_status' => 'closed'
)
);
// Update settings.
affiliate_wp()->settings->set( array(
'affiliates_page' => $affiliate_area
), $save = true );
```
**Basic array of settings …
> Implement saving settings via the Affiliate_WP_Settings::set() method

- .travis.yml
- includes/affiliate-functions.php
- includes/class-affiliates-db.php
- tests/affiliates/test-affiliate-db.php
- tests/affiliates/test-affiliate-functions.php
- tests/misc/test-misc-functions.php
- tests/test-capabilities.php
Issue: #1175 
As part of our ongoing effort to improve test coverage in AWP, let's start with affiliate-functions.php. The goal of this PR is to aim for 100% or near 100% coverage of the file at the time of merging.
As of submission of this PR, this branch constitutes about 60% coverage, up from about 10-15%.
Moar tests incoming.
> issue/1175/affiliate functions – Full test coverage for affiliate-functions.php

- includes/install.php
> issue/1187 – Avoid a fatal on activation by leveraging $affiliate_wp_install instead of affiliate_wp()

- includes/admin/class-notices.php
Issue: #1182 
Adds a default case to the switch statement in `Affiliate_WP_Admin_Notices::dismiss_notices()` along with a new action.
> Issue/1182 – Add a default statement to notices class + new action

- includes/integrations/class-exchange.php
Fixes #1107.
The old hook is maintained for older versions of Exchange.
This introduces a new intermediary method add_coupon_edit_hooks(),
because iThemes Exchange doesn't populate the version global until
after the plugins_loaded hook fires.
> Exchange: Use tabbed coupon interface for affiliate connection

- includes/integrations/class-woocommerce.php
Issue: #1001 
Specifically skips switching a referral status to the default from 'pending' when a COD WooCommerce order is switched to the 'processing' status following successful check out.
> issue/1001 – Skip switching WooCommerce COD order referrals from 'pending'

- includes/affiliate-functions.php
Issue: #1222 
Background:
'affwp_update_affilate' was introduced in 5158fba for #1073.
It conflicts with a dynamic hook fired on form submission. When the edit-affiliate form is submitted, it passes an 'update_affiliate' value to the dynamic `affwp_ . $_REQUEST['affwp_action']` hook. Causes a fatal memory exhaustion error.
> issue/1222 – Rename 'affwp_update_affiliate' action to prevent a fatal

- includes/integrations/class-marketpress.php
The integration didn't support MP 3.0 at all. And it was causing an error on checkout.
See issue report for more context https://premium.wpmudev.org/forums/topic/fatal-error-on-checkout-process-marketpress
> Add support for MarketPress 3.x.

- includes/class-tracking.php
- includes/integrations/class-woocommerce.php
- tests/test-tracking.php
Issue: #1355
Previously, the start-from-scratch approach simply matched for referral and pagination URLs and rebuilt the pagination URLs from scratch, making the assumption no other variables would be in play. This dangerous assumption spawned many edge cases since it was introduced.
The new approach serves to actually try to remove both pretty and ugly referral IDs and usernames from `$link`, accounting for other variables possibly in play in the pagination URLs.
> issue/1355 – Globally remove referral bits from pagination URLs

- includes/misc-functions.php
- includes/objects/class-affwp-affiliate.php
- includes/objects/class-affwp-creative.php
- includes/objects/class-affwp-object.php
- includes/objects/class-affwp-referral.php
- includes/objects/class-affwp-visit.php
Issue: #1450 
Related: #1184, #854 
Instead of trying to make the `$cache_group` in the db classes all things to all classes, statically define `$db_group` at the individual object level for use by the base `\Object` class. Allows us to avoid gymnastics such as dynamically populating the formerly-used `$object_group` when `get_instance()` was  called at the object level. The `$object_group` was able to get polluted because of how it was generated and when.
This approach gives us long term flexibility.
> issue/1450 – Statically define $db_group at the object level, avoiding memory gymnastics

- .gitignore
- Removes `/docs` from ignore list.
- Addresses #1643
> Allow docs dir into core

- includes/affiliate-functions.php
- tests/affiliates/test-affiliate-functions.php
> issue/1656 – Adjust affwp_get_affiliate_rate() to fail gracefully via the filter

- includes/abstracts/class-affwp-reports-tab.php
> issue/1674 – Avoid using $this in a closure when registering Reports tabs

- includes/integrations/class-paypal.php
> issue/1676 – Bail early from the PayPal script if the form action is empty.

- includes/affiliate-functions.php
> issue/1669 – Ensure affiliate rate type won't be null when retrieved

- includes/affiliate-functions.php
- includes/class-affwp-affiliate.php
> Issue/1695 – Revert affwp_get_affiliate_rate() to (mostly) pre-1.9 code.

- includes/integrations/class-paypal.php
> issue/1697 – Explicity bail from the PayPal form handler if action is undefined no match

- includes/abstracts/class-affwp-list-table.php
Issue: #1699 
`add_query_arg()` explicitly checks for a value of false.
> issue/1699 – Variadic parameters are why we can\'t have nice things.

- includes/misc-functions.php
> issue/1714 – Invalidate campaign caches when the item cache is cleaned

- includes/abstracts/class-db.php
> issue/1749 – Pass the $row_id to the affwp_post_update_{$type} hook.

- includes/install.php
> issue/1761 – Set the initial author of the affiliate area page to the user who activated the plugin

- includes/integrations/class-rcp.php
> issue/1780 – Initialize $user_id as 0 to avoid a notice on RCP discount edit.

- includes/integrations/class-edd.php
> issue/1799 - Define $user_id as 0 to avoid a notice on EDD discount edit.

- includes/integrations/class-exchange.php
- includes/integrations/class-memberpress.php
> issue/1815 - Define $user_id as 0 to avoid a notice on the Exchange/MemberPress coupon edit screens.

- affiliate-wp.php
- Uses get_user_locale()` in WordPress 4.7 or greater.
- Falls back to `get_locale()`.
- Related inline hook doc.
#1834
> issue/1834: Add support for user admin locales

- includes/cli/class-creative-sub-commands.php
> issue/1870 – Don't attempt to access a nonexistent $affiliate object in the list() callback

- includes/integrations/class-gravityforms.php
This checks all email fields on the Gravity Form, and if any email matches the affiliate’s email, the referral is blocked.
#1878
> Issues/1878 - Block referral if affiliate’s email is used

- includes/class-tracking.php
Add a leading / to the pattern before the referral var so it can't match the domain part of the url.
**Why?**
Before, if we had a site at `example.com` and set the referral_var to `com`, then our paged urls would look something like `example.page/2`
> Fix a bug where the tld was removed from paged urls when tld==referral_var

- includes/integrations/class-woocommerce.php
- Removes guard clause defined in 1.8, which had the effect of not allowing referral completions in cases where the pot status transitions from processing to completed.
Fixes #1916
> Issue/1916 - Allow referrals from COD orders to be completed

- includes/class-referrals-db.php
- tests/referrals/test-referral-db.php
> issue/1955 – Ensure existing referral affiliate and visit IDs persist if not overwritten

- assets/js/tracking.js
- Add checks for all properties in `affwp_debug_inline_vars`
- Avoid potential conflicts by removing explicit call .values on the affwp_debug_get_integrations Object.
- Ensure the affwp_debug_get_integrations function is safely checked before attempting to return the active integrations
- Provide a notice at the top of AffiliateWP javascript debug info indicating the source and reason for debug being present in the browser console.
- Fixes #1965
> Issue/1965: Resolve conflicts in 2.0 JavaScript debugger

- includes/affiliate-functions.php
- tests/affiliates/test-affiliate-functions.php
> issue/1842 – Bump affwp_get_affiliate_campaigns() to retrieve 100 possible campaigns

- includes/admin/class-notices.php
> issue/2070 – Rename the 'affwp_dismiss_notices' hook to 'affwp_dismiss_notices_default'

- includes/class-login.php
The previous code provides no easy/elegant way for an extension to extend the login form. In my use case, I am developing a plugin which will allow the user to scan a visible code with their smartphone, as a non-compulsory alternative to a password.
This patch provides a filter which allows an extension to instruction Affiliate-WP that it does not need to verify the password (which would be used in the case that the extension has performed its own verification).
Issue: #2120
> Issue/2120 Allow plugins to extend the login form with password alternatives

- includes/class-referrals-db.php
This ensures the referral status never gets unset during update. 
#2072
> Fallback to existing status when updating referral - issue/2072

- includes/class-rewrites.php
> issue/2078 – Skip registering the referral var as a query var in WP 4.3+.

- includes/integrations/class-contactform7.php
Setting up post data was causing problems during CF7 save.
Issue: #2007
> Use get_posts() and not setup post data in get_all_forms() to fix #2007

- includes/integrations/class-stripe.php
Issue: #2261
Part of this fix is the empty description fix in the issue above. There is another part (no GH issue). The second part fixes the check for the Stripe email adress that gets posted. This is changed in WP Simple Pay 3.0.0 and I have added a check for that new value as well as keeping the old value in place for backwards compatibility.
> #2261 Compatibility fix with WP Simple Pay version 3.0.0

- includes/REST/class-rest-authentication.php
- includes/integrations/class-gravityforms.php
The affiliate ID was set up in a local variable before checking if an affiliate coupon was used so the found affiliate ID was never set to the local variable.
Issue: #2278
> Use affiliate ID property instead of local variable. Fixes #2278

- includes/affiliate-functions.php
Add an action that gets fired after the affiliate's data is removed.
It would have been be possible to use the 'affwp_affiliate_deleted' action but only the affiliate ID is passed which means I can't access the user ID (affiliate deleted).
Issue: #
> Add affiliate object to the 'affwp_affiliate_deleted' hook

- includes/admin/settings/class-settings.php
- includes/emails/actions.php
- Adds options to disable additional affiliates emails via `disable_application_accepted_emails`, `disable_new_referral_emails`.
- Moves `registration_notifications` setting to be underneath other disable email options.
- Adds checks for new disabled emails settings in email functions `affwp_notify_on_new_referral` and `affwp_notify_on_approval`.
- #1923
> Issue/1923: Options to disable each email

- includes/class-logging.php
This PR fixes an issue where `wp_upload_dir()` will generate the warning bellow on a read-only filesystem:
```
[03-Oct-2017 07:50:20 UTC]
[Suppressed] Warning: mkdir(): Read-only file system in /var/www/wp-includes/functions.php on line 1624
[wp-includes/functions.php:1624 mkdir(), wp-includes/functions.php:1888 wp_mkdir_p(), wp-content/plugins/affiliate-wp/includes/class-logging.php:28 wp_upload_dir(), wp-content/plugins/affiliate-wp/includes/class-logging.php:16 init(), wp-content/plugins/affiliate-wp/includes/class-utilities.php:91 __construct(), wp-content/plugins/affiliate-wp/includes/class-utilities.php:64 setup_objects(), wp-content/plugins/affiliate-wp/affiliate-wp.php:479 __construct(), wp-includes/class-wp-hook.php:298 setup_objects(), wp-includes/class-wp-hook.php:323 …
```
> Fix warning for wp_upload_dir() on read-only filesystems

- assets/js/tracking.js
- includes/admin/settings/class-settings.php
- includes/class-tracking.php
This PR expands on #2140/#2142 to:
- add a setting to allow sharing tracking cookies with sub-domains (disabled by default)
- automatically use the WP `COOKIE_DOMAIN` constant, if set
This could be considered a breaking change since previously the `COOKIE_DOMAIN` was only used for fallback (server-side) tracking, but not JS tracking.
> Add option to set cookies for sub-domains

- includes/integrations/class-paypal.php
There's a typo when checking if the "action" attr is present in the form element
instead of `if ( 'undefined' === typeof action )`
it's `if ( 'undefined' === action )`
This breaks forms without an action, as it throws an error later when trying to match `action.match( paypalMatch )`
Issue: #2527
> Fix issue with submitting forms without the "action" attribute

- includes/class-tracking.php
> Cookie/visit not created if affiliate username is an email, contains a period when fallback tracking is enabled. Fixes #2539 #2540

- includes/integrations/class-contactform7.php
- includes/integrations/extras/contactform7-functions.php
> Issue/2608 -  Don't log messages in the CF7 integration if Contact Form 7 PayPal add-on is not enabled

- includes/admin/settings/class-settings.php
Issue: #2623
Allow text fields to be disabled but using readonly attribute so the values can still be posted.
> issue/2623 – Allow readonly attributes in setting text fields

- includes/class-visits-db.php
> Issue/2632 - Fix SQL error when using the campaign keyword prefix to search on the Visits page

- includes/integrations/class-woocommerce.php
> Issue/2668 - Revoke unpaid referral if order status transition from processing, completed to failed in WooCommerce integration

- includes/emails/actions.php
> Issue/2695 - Only add password reset link to acceptance email when password field isn't required during registration

- includes/integrations/class-woocommerce.php
> Issue/2704 - Fix leaving "Affiliate Rate" field blank in WooCommerce integration doesn't use default rate

- includes/admin/settings/class-settings.php
> Issue/2726 - Always use the default text in the text_callback() method in the Affiliate_WP_Settings class if the text field is empty.

- includes/integrations/class-stripe.php
> Issue/2692 - Fix description not set for referrals generated through WP Simple Pay
